# global config
debug: false
worker: 4               # number of goroutine to recv update [int]

# bot config
token: ""
black_list:
  enabled: true
white_list:
  enabled: true
restrict:
  kill_duration: 300    # restrict duration for command `kill` [second]
  fake_ban_cd: 1080     # restrict CD for command `kill` or `fake ban xxx` [minutes]
rate_limit:
  max_token: 20         # token bucket size, must [int]
  limit: 0.5            # how many tokens get every seconds [float64]
  cost: 1               # default cost every message [int]
  cost_sticker: 3       # cost of every sticker, sticker message use this cost [int]
  cost_command: 2       # cost of every command, command message use this cost [int]

# redis config
redis:
  addr: "redis:6379"
  pass: "csust-bot-redis-password"

# message config
message:
  links: "NO LINKS"
  restrict_bot: "好 的， 我 杀 我 自 己。"
  fake_ban_in_cd: ""
