version: '3.8'

x-common: &common
  # logging:
  #   driver: loki
  #   options:
  #     loki-url: http://172.17.0.1:3100/loki/api/v1/push
  restart: always

services:

  bot:
    image: csust/csust-got:latest
    container_name: bot
    <<: *common
    restart: always
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/app/config.yaml
    links:
      - redis
    ports:
      - "7777:7777"

  redis:
    image: redis
    container_name: bot-redis
    <<: *common
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    command:
      - /usr/local/etc/redis/redis.conf
