version: '3'

x-log-driver: &log-driver
logging:
  driver: loki-driver
  options:
    loki-url: http://${LOKI_ADDR}:3100/loki/api/v1/push

services:

  bot:
    build: .
    container_name: bot
    <<: *log-driver
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
    container_name: bot-redis
    <<: *log-driver
    logging:
      driver: loki-driver
      options:
        loki-url: http://${LOKI_ADDR}:3100/loki/api/v1/push
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    command:
      - /usr/local/etc/redis/redis.conf
