name: Deployment

on:
  workflow_run:
    workflows: ["Docker Build And Push"]
    branches: [ dev, master ]
    types: [ completed ]

jobs:

  deploy:
    name: "Deployment"
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:

      - name: "Get source"
        uses: actions/checkout@v2
      
      - name: "Print Version"
        id: "version"
        run: |
          echo "Version:" $(git branch --show-current)-$(git rev-parse --short HEAD)
          echo "::set-output name=branch::$(git branch --show-current)"
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

      - name: Develop Deployment
        uses: appleboy/ssh-action@master
        if: steps.version.outputs.branch == 'dev'
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd survey && docker-compose pull && docker-compose up -d
      
      - name: Release Deployment
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'release')
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd survey && docker-compose pull && docker-compose up -d
