name: Deployment

on:
  workflow_run:
    workflows: 
      - Docker Build
    branches:
      - master
      - dev
    types:
      - completed

jobs:

  deploy:
    name: "Deployment"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Get source
        uses: actions/checkout@v2
      
      - name: Print version
        id: "version"
        run: |
          echo "::set-output name=branch::$(git branch --show-current)"

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.ref }}
          check-name: Test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Develop Deployment
        uses: appleboy/ssh-action@master
        if: steps.version.outputs.branch == 'dev' && startsWith(github.ref, 'refs/tags/v') == false
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.PRIVATE_KEY_DEV }}
          script: cd csust-got && docker-compose pull && docker-compose up -d
      
      - name: Release Deployment
        uses: appleboy/ssh-action@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd csust-got && docker-compose pull && docker-compose up -d
