name: Docker Image Push

on:
  push:
    branches: [ dev, master ]
    

jobs:
          
  docker_build:
    name: "build and push docker image"
    runs-on: ubuntu-latest
    steps:
      
      - name: "Get source"
        uses: actions/checkout@v2
      
      - name: "Print Version"
        id: "version"
        run: |
          echo "Version:" $(git branch --show-current)-$(git rev-parse --short HEAD)
          echo "::set-output name=branch::$(git branch --show-current)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push when push to 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ steps.setup-buildx.outputs.platforms }}
          tags: |
            csust/csust-got:latest-${{ steps.version.outputs.branch }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
