name: Docker Image Push

on:
  release:
    types: [ published ]

jobs:

  docker_build:
    name: "build and push docker image when release"
    runs-on: ubuntu-latest
    steps:

      - name: "Get source"
        uses: actions/checkout@v2

      - name: "Print Version"
        id: version
        run: |
          echo "Version:" $(git branch --show-current)-$(git rev-parse --short HEAD)
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=platforms::linux/arm/v7,linux/arm/v6,linux/arm64,linux/386,linux/amd64"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Get deps
        run: go mod vendor

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push when push to 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ steps.version.outputs.platforms }}
          tags: |
            csust/csust-got:latest
            csust/csust-got:${{ steps.version.outputs.tag }}
          build-args: |
            TAG=${{ steps.version.outputs.tag }}
            BRANCH=release
            RELEASE=release

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Docker Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd csust-got && docker-compose pull && docker-compose up -d
