name: Pull Request

on:
  pull_request:

jobs:

  lint:
    name: Lint
    uses: CSUSTers/csust-got/.github/workflows/lint.yml@dev


  test:
    name: Test
    uses: CSUSTers/csust-got/.github/workflows/test.yml@dev


  go-build:
    name: Go Build
    uses: CSUSTers/csust-got/.github/workflows/go-build.yml@dev
