name: Push Build

on:
  push:
    branches:
      - dev
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Get source
        uses: actions/checkout@v2

      - name: Get deps
        run: make deps

      - name: Test
        run: make test


  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            goarch: amd64
            goarm:
          - platform: linux/386
            goarch: 386
            goarm:
          - platform: linux/arm64
            goarch: arm64
            goarm:
          - platform: linux/arm/v7
            goarch: arm
            goarm: 7
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Get source
        uses: actions/checkout@v2

      - name: Print version
        id: "version"
        run: |
          echo "Version:" $(git branch --show-current)-$(git rev-parse --short HEAD)
          echo "::set-output name=branch::$(git branch --show-current)"

      - name: Build bot
        run: GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} make deploy

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            csust/csust-got:latest-${{ steps.version.outputs.branch }}


  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:

      - name: Get source
        uses: actions/checkout@v2
      
      - name: Print version
        id: "version"
        run: |
          echo "::set-output name=branch::$(git branch --show-current)"

      - name: Deployment
        uses: appleboy/ssh-action@master
        if: steps.version.outputs.branch == 'dev'
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.PRIVATE_KEY_DEV }}
          script: cd csust-got && docker-compose pull && docker-compose up -d
