name: Release

on:
  release:
    types:
      - published

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Get source
        uses: actions/checkout@v2

      - name: Get deps
        run: make deps

      - name: Test
        run: make test


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Get source
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          tags: |
            csust/csust-got:latest
            csust/csust-got:${{ github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name }}
            BRANCH=release


  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd csust-got && docker-compose pull && docker-compose up -d
