name: Test

on:
  push:
    branches:
      - dev
      - master
  pull_request:

jobs:

  test:
    name: "Run Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Get source
        uses: actions/checkout@v2

      - name: Get deps
        run: make deps

      - name: Test
        run: make test
